application: sudoku-solver
version: 2
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /img/favicon\.ico
  static_files: public/img/favicon.ico
  upload: public/img/favicon\.ico

- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /
  script: public/index.php